### ISSUE TITLE
Quotes within custom property values break implementation

### ISSUE THREAD

**Issue by hamlim** [zeit/styled-jsx#150]
Just got started setting up next and styled-jsx, and noticed that when setting custom properties such as font-families, the quoted font families will break the parser.

```
:root {
  --fonts: -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    Roboto,
    Oxygen-Sans,
    Ubuntu,
    Cantarell,
    "Helvetica Neue",
    sans-serif;
} 
html {
  font-family: var(--fonts);
}
```

The value that gets parsed and sent into the `style` tag is then:
```
--fonts: -apple-system, BlinkMacSystemFont, &quot;
```

Removing the quoted font families resolves the issue.

**Comment by giuseppeg** [comment]
@thysultan could this be a bug in Stylis?

**Comment by thysultan** [comment]
@giuseppeg I don't think so, stylis doesn't generate `&quot;` markup, i'm getting the following css generated.

```scss
:root {
--fonts: -apple-system, 
	BlinkMacSystemFont, 
	"Segoe UI", 
	Roboto, 
	Oxygen-Sans, 
	Ubuntu, 
	Cantarell,
	"Helvetica Neue",sans-serif;
}

html {
	font-family: var(--fonts);
}
```
