### ISSUE TITLE
Join :global selectors

### ISSUE THREAD

**Issue by Idered** [zeit/styled-jsx#158]
Right now this is supported:

```css
.List :global(>) :global(*) {
  margin-top: 10px;
}

.List :global(*) :global(+) :global(*) {
  margin-top: 10px;
}
```

and this is not supported:

```css
.List :global(> *) {
  margin-top: 10px;
}

.List :global(* + *) {
  margin-top: 10px;
}
```

Can we make it any better?
