### ISSUE TITLE
Minification breaks descendant selectors in v1.0.0

### ISSUE THREAD

**Issue by ifyio** [zeit/styled-jsx#211]
This

```css
<style jsx global>
  .Input.is-invalid .Input-messageText {
    color: rgb(244, 0, 71);
  }
</style>
```

gets converted to

```css
.Input.is-invalid.Input-messageText{color:rgb(244, 0, 71)}
```

Note that there is no space between `.Input.is-invalid.` and `.Input-messageText`

**Comment by giuseppeg** [comment]
@thysultan this seems like a bug in Stylis to me

**Comment by soulchainer** [comment]
I can't say it isn't (I'm not an expert) @giuseppeg , but you can check it quick if something it's correctly parsed by `stylis` cloning their project and open in your browser the path `/docs/index.html`. This opens a playground, @ifyio, and I checked your example code and it gets converted to:

```css
.component-x .Input.is-invalid .Input-messageText {
	color: rgb(244, 0, 71);
}
```

(The `.component-x` it's because it's using `scope` by default) and... that's a correct output >_<.
So, I think that seems like a minification phase error, yup. IDK if the minification it's done also but `stylis` after that or what.
