### ISSUE TITLE
Faulty nesting detection with at-rules

### ISSUE THREAD

**Issue by cheeaun** [zeit/styled-jsx#214]
I upgraded to the latest version of `styled-jsx` at `1.0.1` and been getting this error:

```
[Error: Nesting detected at 0:80. Unfortunately nesting is not supported by styled-jsx.]
```

Did a little research, ran tests on both `styled-jsx` and `stylis`, found that:

```js
test("doesn't throw when using media queries", t => {
  t.notThrows(() =>
    transform('', '@media (min-width: 480px) { div { color: red } }')
  )
})
```

This is the current test and it **passes** ✅ 

```js
test("doesn't throw when using media queries", t => {
  t.notThrows(() =>
    transform('', 'span {} @media (min-width: 480px) { div { color: red } }')
  )
})
```

Added a faux `span` and this **passes** too ✅ 

BUT...

```js
test("doesn't throw when using media queries", t => {
  t.notThrows(() =>
    transform('', `span {}
      @media (min-width: 480px) { div { color: red } }`)
  )
})
```

Add a newline and this **fails** ❌ 

```js
test("doesn't throw when using media queries", t => {
  t.notThrows(() =>
    transform('', `@media (min-width: 480px) { div { color: red } }
      span {}`)
  )
})
```

If the lines are flipped around, this **passes** ✅  😅 

I suspect this is relevant to the`disableNestingPlugin` method in `style-transform.js` **and** the `cascade: false` option passed into `stylis`. This applies to `@keyframes` too.

**Comment by giuseppeg** [comment]
@cheeaun thanks for the great and detailed bug report! You are correct the bug should be in `disableNestingPlugin` or Stylis itself.

Would you have time to further debug `disableNestingPlugin`? If not I will take a look at it tonight or tomorrow. You can find the relevant docs here https://github.com/thysultan/stylis.js#plugins

**Comment by cheeaun** [comment]
@giuseppeg I've also tried to replicate the bug on `stylis`, with the exact same CSS code and even the same config `{cascade: false, compress: true}`. It passes ✅  there.

I suspect that when `cascade: false`, the `context` becomes different (`2`) or something (I `console.log`-ed everything in the `disableNestingPlugin` method). So I'm not sure if it needs special handling in the method or `context` is wrongly handled here 🤔

**Comment by thysultan** [comment]
`div { color: red }` is a parent of `@media (min-width: 480px)` so you may need to take that into account by allowing @at-rules as parents, e.x making an exception when the first character is `@`

**Comment by giuseppeg** [comment]
@thysultan yep that indeed fixes @cheeaun's issue. Mind taking a look at the PR #216 ?

However there seem to be a bug in Stylis and media queries are prefixed

```css
span {}
      @media (min-width: 480px) { div { color: red } }

/* @media[prefix](min-width[prefix]:480px[prefix]) div[prefix]{color:red} */
```

```css
:hover {}
      @media (min-width: 480px) { div { color: red } }

/* @media[prefix](min-width[prefix]:480px[prefix]) div[prefix]{color:red} */
```

```css
:hover { color: green }
  @media (min-width: 480px) { div { color: red } }

/* [prefix]:hover{color:green}@media[prefix](min-width[prefix]:480px[prefix]) div[prefix]{color:red} */
```
