### ISSUE TITLE
Pseudo classes and elements broken in recent version

### ISSUE THREAD

**Issue by jaydenseric** [zeit/styled-jsx#219]
Since upgrading `next@3.0.0-beta6` to `next@3.0.0-beta8`, chained pseudo classes such as `:not()` and `:disabled` are broken. I assume this is due to a newer version of styled-jsx. I tried the same styles using https://stylis.js.org without the issue appearing, so it must be something to do with styled-jsx?

With this contrived example:

```jsx
const Textarea = props => (
  <div>
    <textarea {...props} />
    <style jsx>{`
      textarea:not(:focus) {
        border-color: blue;
      }
      textarea:not(:focus):disabled {
        opacity: 0.5;
      }
    `}</style>
  </div>
)
```

Before update (correct):

```css
textarea[data-jsx="451418276"]:not(:focus) {
  border-color: blue;
}

textarea[data-jsx="451418276"]:not(:focus):disabled {
  opacity: 0.5;
}
```

After update (incorrect):

```css
textarea[data-jsx="451418276"]:not([data-jsx="451418276"]:focus) {
  border-color: blue;
}

textarea[data-jsx="451418276"]:not([data-jsx="451418276"]:focus) [data-jsx="451418276"]:disabled {
  opacity: 0.5
}
```

**Comment by jaydenseric** [comment]
- Worked: [styled-jsx@0.5.7](https://github.com/zeit/next.js/blob/3.0.0-beta6/package.json#L90).
- Not working: [styled-jsx@1.0.3](https://github.com/zeit/next.js/blob/3.0.0-beta8/package.json#L89).

@thysultan nothing comes to mind?

**Comment by sidorares** [comment]
having same issue ( hi @jaydenseric ! ) 
`:before` selector not working since updating to next@2.4.1 today

**Comment by thysultan** [comment]
I'll look into this

@sidorares How does your input vs output look like?
@jaydenseric [https://stylis.js.org](https://stylis.js.org) Does not use cascade isolation so it might not show there.

**Comment by thysultan** [comment]
@jaydenseric Is the first one still valid? e.x doesn't `[data-jsx="451418276"]` just increase specificity for the `:focus` pseudo?

```css
textarea[data-jsx="451418276"]:not([data-jsx="451418276"]:focus)
```

**Comment by sidorares** [comment]
@thysultan was: `.submit-status-yes[data-jsx="1547817510"]:before`, after update to next@2.4.1 ( styled-jsx 1.0.3 ) -  `.submit-status-yes:before[data-jsx="1547817510"]`

**Comment by jaydenseric** [comment]
@thysultan No, it is not valid. `:not()` only accepts a single simple selector.

Invalid:

```css
textarea[data-jsx="451418276"]:not([data-jsx="451418276"]:focus) {
  border-color: blue;
}
```

Valid:

```css
textarea[data-jsx="451418276"]:not([data-jsx="451418276"]):not(:focus) {
  border-color: blue;
}
```
