### ISSUE TITLE
@font-face broken?

### ISSUE THREAD

**Issue by danielsarin** [zeit/styled-jsx#237]
I'm using styled-jsx 1.0.4 with next.js 3.0.0-beta12, and it seems like something breaks when using  font-face.

My code looks something like this:
```jsx
<div>
  ...
  <style jsx global>{`
    @font-face {
      font-family: 'Icons';
      src:
        url('/static/fonts/vuo-icons/Icons.ttf?4kyjpv') format('truetype'),
        url('/static/fonts/vuo-icons/Icons.woff?4kyjpv') format('woff'),
        url('/static/fonts/vuo-icons/Icons.svg?4kyjpv#Icons') format('svg');
      font-weight: normal;
      font-style: normal;
    }
  ...
  `}</style>
</div>
```
but when I look at the content in dom style tags that are rendered in head, it comes out like this:
```css

@font-face {
  font-family: 'Icons';
  src: ;
    url('/static/fonts/vuo-icons/Icons.ttf?4kyjpv') format('truetype'),
    url('/static/fonts/vuo-icons/Icons.woff?4kyjpv') format('woff'),
    url('/static/fonts/vuo-icons/Icons.svg?4kyjpv#Icons') format('svg');
  font-weight: normal;
  font-style: normal
}
```
For some reason, there is an extra semi-colon right after `src:` which breaks the css.

Is it possible I am doing something wrong? Otherwise this seems like a bug to me.
