### ISSUE TITLE
Mixing Internal and External styles doesn't work as expected.

### ISSUE THREAD

**Issue by hamlim** [zeit/styled-jsx#259]
## Issue:
I have a use case for overriding some default styles based on the global context a shared component is rendered within. To do this I attempted the following pattern:

```Javascript
import styleOverrides from './style_overrides';

const MyComponent = (props) => (
  <div>
    // ... component internals here //
    <style jsx>{`
      .class {
        /* default styles here */
      }
      ${styleOverrides}
    `}</style>
  </div>
);
```

## Expected Outcome:
The expected outcome here would be that the internal styles get overridden by any duplicate content from `styleOverrides`, like so:

```CSS
// computed css
.class { // external styles
  color: red;
}
.class { // internal styles
  color: blue;
}
```

## Actual Outcome:

I have seen two different outcomes, one was from a re-wired Create-React-App project, and another was in this repo I made to demonstrate the bug: 
https://github.com/hamlim/styled-jsx-external-plus-internal-bug

The css generated from the demo linked above looks like this:
```
<style>[data-jsx="3949331497"]{h1{color:red}
h1[data-jsx="3949331497"]{color:blue}</style>
```
(omitted source map content)
This causes the `<h1>` to be blue.

**Comment by hamlim** [comment]
Edit: Looks like an issue with how the [data-jsx] attribute selector is added because it generates this:

```CSS
[data-jsx="[hash]"]{
  .class { 
    color: red; 
  }
}
```

Which is invalid css and therefore ignored.
