### ISSUE TITLE
non-"Proof of Concepts" Plugins?

### ISSUE THREAD

**Issue by jthegedus** [zeit/styled-jsx#350]
Each of the [linked plugins](https://github.com/zeit/styled-jsx#example-plugins) are prefaced with
>Warning this is a Proof Of Concept plugin

Are these planned to become full-fledged packages or should we shy away from these and have the community build their own?

**Comment by giuseppeg** [comment]
> have the community build their own

Is the way to go, I don't have the time to maintain them. I will try to make the experience better by providing a built in solution to work with interpolations (since they are not valid css and can be troublesome when making a plugin).

**Comment by jthegedus** [comment]
@giuseppeg So should one wait for your work on
>experience better by providing a built in solution to work with interpolations

Or is the API not likely to change too much?

**Comment by giuseppeg** [comment]
I might change how placeholders for interpolations are represented eg.

```css
/* existing */
@media (min-width: %%styled-jsx-placeholder-0%%) {  /* something ... */ }

/* better */
@media (min-width: %%styled-jsx-placeholder-value-0%%) {  /* something ... */ }

/* existing */
div {
   %%styled-jsx-placeholder-0%%;
   color: red;
}

/* better */
div {
   %%styled-jsx-placeholder-rulesblock-0%%;
   color: red;
}
```

basically define a set of standard tokens so it is easier to replace placeholders in plugins:

```
%%styled-jsx-placeholder-TOKEN_TYPE-0%%
```
