### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Pro542** [zeit/styled-jsx#363]
What would be the best way to go about RTL css? I was expecting something like below to work, and was trying to use postcss-rtl to get the required styles. (I believe it doesn't work since the selectors are not matched at compile time)
```css
[dir] h1 {
    margin-left: 10px;
}
[dir=ltr] h1 {
    margin-left: 10px;
}
[dir=rtl] h1 {
    margin-right: 10px;
}
```
Otherwise, would using a toggle in JS to select the appropriate style the way to go? This would mean I won't be able to auto generate the styles and have to write RTL css manually.

**Comment by giuseppeg** [comment]
What exactly doesn't work about your example above? Can you share your experimental code? Maybe make a Next.js app

**Comment by Pro542** [comment]
The above style can be written like this to make it work:
```css
:global(html[dir=rtl]) h1 {
    margin-right: 10px;
}
```
I'm setting `dir` on `html` based on a URL key and deciding the styles to be applied from that. Will share a temp app soon
