### ISSUE TITLE
Using @support inside @media discards a closing curly brace

### ISSUE THREAD

**Issue by matt-hernandez** [zeit/styled-jsx#370]
I have this chunk of code in one of my components

```jsx
<style jsx global>{`
  @media (max-width: 64em) {
    .halves-3uXAK.clearBottom-1bMlY ul {
      margin-bottom: -4.34783%;
    }
    @supports (-moz-appearance: none) and (display: contents) {
      .halves-3uXAK.clearBottom-1bMlY ul {
        margin-bottom: -2rem;
      }
    }
  }
`}</style>
```

The resulting CSS in the `<head>` comes out like this:

```css
@media (max-width:64em) {
  .halves-3uXAK.clearBottom-1bMlY ul {
    margin-bottom: -4.34783%;
  }
  @supports (-moz-appearance:none) and (display:contents) {
    .halves-3uXAK.clearBottom-1bMlY ul {
      margin-bottom: -2rem;
    }
  }

/* ^^^ There is a missing closing curly brace above */
```

**Comment by matt-hernandez** [comment]
I noticed something. This bug only occurs when `@supports` is the last block in `@media`. If another css rule comes after it, the transpilation occurs without error.

Example:

```jsx
<style jsx global>{`
  @media (max-width: 64em) {
    .halves-3uXAK.clearBottom-1bMlY ul {
      margin-bottom: -4.34783%;
    }
    @supports (-moz-appearance: none) and (display: contents) {
      .halves-3uXAK.clearBottom-1bMlY ul {
        margin-bottom: -2rem;
      }
    }
    .oneMoreRule {
      width: 0;
    }
  }
`}</style>
```

Turns into this

```css
@media (max-width:64em) {
  .halves-3uXAK.clearBottom-1bMlY ul {
    margin-bottom: -4.34783%;
  }
  @supports (-moz-appearance:none) and (display:contents) {
    .halves-3uXAK.clearBottom-1bMlY ul {
      margin-bottom: -2rem;
    }
  }
  .oneMoreRule {
    width: 0;
  }
}

/* Everything looks good! */
```

**Comment by giuseppeg** [comment]
@thysultan can this be a bug in Stylis?

**Comment by thysultan** [comment]
@giuseppeg I get the following(minus whitespace) with stylis(inc the different configs)

```css
@media (max-width:64em){
	.halves-3uXAK.clearBottom-1bMlY ul{
		margin-bottom:-4.34783%
	}
	@supports (-moz-appearance:none) and (display:contents){
		.halves-3uXAK.clearBottom-1bMlY ul{
			margin-bottom:-2rem
		}
	}
}
```
So it doesn't look it is from stylis.
