### ISSUE TITLE
Using styled-jsx to merge traditional CSS with modern JS??

### ISSUE THREAD

**Issue by KingScooty** [zeit/styled-jsx#394]
So i really want to get into using CSS in JS, but i really feel a lot of the time it's an "all or nothing" solution to a problem that mostly goes away if you just write well structured, namespaced CSS. It's great for components like a "button", but gets quite clunky when doing bigger things. Things that would be quite fast to write in vanilla HTML and CSS end up needing a React component and then tests, and it just gets a bit too unnecessarily abstract (like grids etc).

I'm a big fan of NextJS. And normally i include a `base.css` full of reusable patterns (written in Sass) in the head, and then start writing my app—only really using CSS in JS (styled-jsx) to enrich the patterns used in my `base.css`. 

But a lot of the time, 50% of that css file goes to waste. It's not used in the app, which results in unnecessary downloaded bytes. This is why CSS in JS appeals to me, as you get dead code elimination for free.

I'd really like to convert my CSS pattern library (a group of reusable CSS objects, that just structure content, and don't add any visual styling like colours etc) to use something like styled-jsx. The idea would be if i exported each block small enough, I could just import the sections each component needed and then i'd get a ton of dead code elimination as i visit each page.

I'm trying out a few things, and would really like someone's input on whether i've completely lost the point with this CSS in JS stuff, or whether there's some sense in what i'm doing. 

Here's an example of a CSS pattern called the block pattern that i've attempted to port over. 

```css
import css from 'styled-jsx/css';
import { globalSpacingUnit, spacingUnit } from '../settings/settings';

/* ==========================================================================
#BLOCK
========================================================================== */

/**
 * Stacked image-with-text object. A simple abstraction to cover a very commonly
 * occurring design pattern.
 */

export base css`
.o-block {
    display: block;
    text-align: center;
}

.o-block__img {
    margin-bottom: ${globalSpacingUnit}px;
}

.o-block__body {
    display: block;
}
`;

/* Size variants
====================================================================== */

export const flush = css`
.o-block--flush > .o-block__img {
    margin-bottom: 0;
}
`;

export const tiny = css`
.o-block--tiny > .o-block__img {
    margin-bottom: ${spacingUnit.tiny}px;
}
`;

export const small = css`
.o-block--small > .o-block__img {
    margin-bottom: ${spacingUnit.small}px;
}
`;

export const large = css`
.o-block--large > .o-block__img {
    margin-bottom: ${spacingUnit.large}px;
}
`;

export const huge = css`
.o-block--huge > .o-block__img {
    margin-bottom: ${spacingUnit.huge}px;
}
`;

/* Alignment variants
========================================================================== */
export const right = css`
.o-block--right {
    text-align: right;
}
`;

export const left = css`
.o-block--left {
    text-align: left;
}
`;
```

This could then be consumed in a component like so:

```js
import React from 'react';
import { base, small, right }  from '../jss/objects/block';

export default () => (
	<div>
		<style jsx global>{base}</style>
		<style jsx global>{small}</style>
		<style jsx global>{right}</style>
		<div className="o-block o-block--small o-block--right">
			<div className="o-block__img">
				<img src="https://placeimg.com/400/200/animals" alt=""/>
			</div>
			<div className="o-block__body">
				<p>This is some text.</p>
			</div>
		</div>
	</div>
);

```

I see these patterns as global styles. Then custom styling like colours can be scoped on the component. 

What i notice straight away is there would be a hell of a lot of `style` tags if i did this. Is that scalable? Or am i going to hit problems?

Have i got the right idea? Or am i using `styled-jsx` wrong?

Another way i could do it is be a bit more clever with the composition of my styled jsx rules, as each of the variants in that css-jsx file _depend_ on the `base` class/variable. So is there a way i can merge the rules?

Example:

```css
export const base = css`
.o-block {
    display: block;
    text-align: center;
}

.o-block__img {
    margin-bottom: ${globalSpacingUnit}px;
}

.o-block__body {
    display: block;
}
`;

/* Size variants
====================================================================== */

export const flush = css`
{ ...base } /* <--- Some way to describe css class dependencies?? */
.o-block--flush > .o-block__img {
    margin-bottom: 0;
}
`;
```

`flush` _*requires*_ `base` in order to work. I'm keen not to lose my syntax highlighting by removing the `css` function call, so it would be cool if i could say that `flush` requires `base` as a dependency. 

That way, i'd only need to do: 

```js
<style jsx>{flush}</style>
``` 

Instead of:

```js
<style jsx>{base}</style>
<style jsx>{flush}</style>
```

What are people's thoughts?

I'm aware styled jsx is string based, and not object based (is that still true?), but if the styles are broken down small enough, importing just the bits you need should still be really beneficial.

I can definitely see that there's power in CSS in JS, but i'd really like to merge old world with new world. Traditional CSS enriched with JS to take advantage of the added benefits without losing the flexibility of writing raw HTML and CSS.
