### ISSUE TITLE
Passing variable string is parsed even if it shouldn't

### ISSUE THREAD

**Issue by Kenjirou** [zeit/styled-jsx#415]
Example:

I need to add animations for SVG
```javascript
<style jsx>{`
    svg:hover path {
        transition: d 0.5s ease-in-out;
        d: path(${pathString});
    }
`}</style>
```

For example `pathString` at that moment contains "M2,5 C2,8 8,8 8,5" value. So it should be parsed to something like this:
```css
svg:hover path {
    transition: d 0.5s ease-in-out;
    d: path("M2,5 C2,8 8,8 8,5");
}
```

But we now have something like this (value that is passed to `path()` is without quotes):
```css
svg:hover path {
    transition: d 0.5s ease-in-out;
    d: path( M2,5 C2,8 8,8 8,5 );
}
```
