### ISSUE TITLE
Comment before corrupts keyframes

### ISSUE THREAD

**Issue by jaydenseric** [zeit/styled-jsx#433]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What is the current behavior?

Adding a comment before keyframes corrupts the keyframes. Discovered when searching for a workaround to https://github.com/zeit/styled-jsx/issues/432.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

In:

```jsx
const FadeIn = ({ children }) => (
  <div>
    {children}
    <style jsx>{`
      /* Comment. */
      @keyframes fadeIn {
        from {
          opacity: 0;
        }
      }
      div {
        animation: fadeIn 1s;
      }
    `}</style>
  </div>
)
```

Out:

```css
@keyframes fadeIn from.jsx-4218845107{opacity:0;}div.jsx-4218845107{-webkit-animation:fadeIn-jsx-4218845107 1s;animation:fadeIn-jsx-4218845107 1s;}
```

I don't think this is a stylis issue, because adding this input in [stylis.js.org](https://stylis.js.org) seems to work ok:

```css
/* @scope .component-x */

/* Comment. */
@keyframes bar {
  0% {
    opacity: 0;
  }
}
```

#### What is the expected behavior?

Valid CSS keyframes are created:

```css
@-webkit-keyframes fadeIn-jsx-4272462935{from{opacity:0;}}@keyframes fadeIn-jsx-4272462935{from{opacity:0;}}div.jsx-4272462935{-webkit-animation:fadeIn-jsx-4272462935 1s;animation:fadeIn-jsx-4272462935 1s;}
```

#### Environment (include versions)

* OS: macOS v10.13.4
* Browser: Chrome v65.0.3325.181
* styled-jsx (version): v2.2.6

#### Did this work in previous versions?

Unsure.
