### ISSUE TITLE
unwanted prefix in media query

### ISSUE THREAD

**Issue by leiyangyou** [zeit/styled-jsx#463]
#### Do you want to request a *feature* or report a *bug*?

*bug*

#### What is the current behavior?

```css
      @media (max-width: 100px) {
        header {
          display:block;
        }
      }
```
produces
```css
@media (max-width.jsx-3196607271:100px) header{display:block;}
```
#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1.
2.

#### Environment (include versions)

* styled-jsx (version): 2.2.6

#### Did this work in previous versions?

Not sure

what is weird is this, manually calling stylius with the same css does produce the correct result
