### ISSUE TITLE
SASS transformation

### ISSUE THREAD

**Issue by rauchg** [zeit/styled-jsx#5]
Probably outside the scope of this module, but we could document how to make this work:

```js
<script jsx type="text/sass">{`
  p {
    color: red;
    & a {
       color: #fff;
    }
  }
`}</script>
```

**Comment by thysultan** [comment]
I'm looking into adding this to stylis, ping me if you have implementation ideas.

**Comment by operatino** [comment]
Having a documentation about how to add own css transformation rules would be really useful.

> Note: whoever writes this transformation must be aware that we auto-prefix already.

Btw, this is also important part missing in docs. Autoprefixing should be at least configurable to define supported browsers.

**Comment by drcmda** [comment]
@rauchg @operatino why not simply do it like csjs? They allow compile time babel transforms:

Links:
https://github.com/tizmagik/react-csjs
https://github.com/rtsao/babel-plugin-csjs-postcss

That way any postCSS transform can run over the css. You could safely remove the autoprefixer as its no longer needed.

**Comment by thysultan** [comment]
So i already got a working version of this for stylis that i'll push with the next release and it's only like ~40 lines so i'm pretty impressed with the results, the way it works is when it finds a block it skips it but adds it as a block to the end of the string buffer namespaced to it's parent, when the parser finally comes across it again the same thing will happen for any nested blocks within it, recursively until there are no more nested blocks.

so this...

```css
h1, div {
        color: red;

	h2, &:before {
		color: red;
	}
        
       color: blue;

	header {
		font-size: 12px;
	}
}
```

becomes this...

```css
h1, 
div { color: red; color: blue; }

h1 h2,
h1:before,
div h2,
div:before { color: red; }

h1 header,
div header{ font-size: 12px; }
```
