### ISSUE TITLE
Incorrect styles in scope for @font-face

### ISSUE THREAD

**Issue by DmitryKozyrenko** [zeit/styled-jsx#504]
#### Do you want to request a *feature* or report a *bug*?
*bug*

#### What is the current behavior?
incorrect styles in scope.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar
I think this screens can say all about issue, error occured when we try to write "src" for our "@font-face" and add "format()":
screen with styles in next.js 6.1.2 https://i.imgur.com/h6wL2LF.png, as you can see we have correct space between "url()" and "format()".
On next.js 7.0.1 (styled-jsx 3.1.0) we have inexplicable ":" betwen them https://i.imgur.com/xlibMku.png, and also want to note this will appears only in the first "src".
Styles writed in the <style jsx global/> but this will fail and in <style jsx/> too.

#### What is the expected behavior?
correct styles in scope.

#### Environment (include versions)

* OS: Windows / Linux
* Browser: node
* styled-jsx (version): 3.1.0

#### Did this work in previous versions?
Working with next.js 6.1.2.

**Comment by giuseppeg** [comment]
@DmitryKozyrenko can you provide a snippet of CSS so that I can test this

**Comment by artshipulin** [comment]
We're having a similar issue: `local('Roboto Condensed')` becomes `local("Roboto:Condensed")`. Here is a snippet of CSS to test with:

```css
@font-face {
	font-family: 'Roboto Condensed';
	font-style: normal;
	font-weight: 400;
	src: local('Roboto Condensed'), local('RobotoCondensed-Regular'),
	     url('/static/fonts/roboto-condensed-v16-latin-regular.woff2') format('woff2'),
	     url('/static/fonts/roboto-condensed-v16-latin-regular.woff') format('woff');
	font-display: fallback;
}
```
