### ISSUE TITLE
Trailing comma bug

### ISSUE THREAD

**Issue by gilbert** [zeit/styled-jsx#554]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What is the current behavior?

Leaving a trailing comma on a selector causes the rule to affect all elements. Example:

```css
table td,
table tbody tr, { /* <-- trailing comma */
  border: 1px solid #ccc;
}
```

#### What is the expected behavior?

Should throw a syntax error since it's not valid css.

#### Environment (include versions)

* OS: OS X Mojave
* Browser: Safari
* styled-jsx (version): 3.2.1

#### Did this work in previous versions?

Not sure
