### ISSUE TITLE
CSS compiler issues: comments and commas

### ISSUE THREAD

**Issue by rauchg** [zeit/styled-jsx#57]
The following doesn't compile well, unless I take out the comment

```css
.story {
  /* todo: probably a more flex-y way of doing this? */
  flex: 100;
  display: inline-block;
}
```

And based on how stylis.js was originally written, it uses `split` with `,` for selectors, where it should actually keep track that the `,` is not inside a selector for example., so this will break:

```css
.story[title=","] {
  display: inline-block;
}
```
