### ISSUE TITLE
Support auto generation of RTL styles

### ISSUE THREAD

**Issue by HosseinAgha** [zeit/styled-jsx#586]
### Do you want to request a *feature* or report a *bug*?
feature

### What is the current behavior?
There is no official way to auto generate right-to-left css.  
What I mean by auto generation is the following:  

```css
// before generating rtl styles
.container {
   margin-right: 6px;
   padding-right: 6px;
   background: red;
   /*rtl:ignore*/
   text-align: left;
}

// after generating rtl styles
[dir=rtl] .container {
  margin-left: 6px;
  padding-left: 6px;
} 

[dir=ltr] .container {
  margin-right: 6px;
  padding-right: 6px;
} 

.container {
  background: red;
  text-align: left;
}
```

PostCSS has [postcss-rtl](https://github.com/vkalinichev/postcss-rtl) plugin which uses very famous, super mature [rtlcss](https://github.com/MohammadYounes/rtlcss) library.

I tried to use it with `styled-jsx-plugin-postcss` and got some interesting results.

1. Global Static Styles: Works fine (changing the `html[dir]` instantly changes the direction)

2. Scoped Static Styles: Works fine using the following trick 
    using the [postcss-rtl](https://github.com/vkalinichev/postcss-rtl)'s `addPrefixToSelector` function I changed the `[dir=x]` prefixes to `:global([dir=x])`

3. Global and Scoped Dynamic Styles: Duplicates the styles for RTL direction

the code:
```jsx
{/* props.border is '12px solid red' */}
<style jsx global>{`
    .container {
      border-left: ${props.border};
    }
`}</style>
```

the generated dynamic style:
```css
[dir=ltr] .container {
   border-left: 12px solid red;
}

// duplicate `12px solid red`
[dir=rtl] .container {
   border-right: 12px solid red12px solid red;
}
```

#### Solution

I think with a little effort we can add one of the best auto RTL css-in-js solutions using the precompiled nature of styled-jsx.  
The [`styled-components` RTL support](https://github.com/styled-components/styled-components/search?q=rtl&type=Issues) is mostly based on [stylis-rtl](https://github.com/FindHotel/stylis-rtl) which is not as mature as [rtlcss](https://github.com/MohammadYounes/rtlcss) and definitely has a long way to cover all RTL css generation edge cases.  

I'd be happy to contribute if you guide me on what do you think the issue is.
