### ISSUE TITLE
styled-jsx cannot return a list of rules, only a list of selectors

### ISSUE THREAD

**Issue by scabbiaza** [zeit/styled-jsx#624]
Hello!
Guys, I’m moving my project to `styled-jsx`. So far so good. Thank you for this concept and for all the integrations!

---

#### `styled-jsx` cannot return a list of rules, only selectors

Let me give you an example to understand the case. 

In LESS I used mixins to extend a list of rules in a selector, for example:

```less
.circle(@size) {
  border-radius: 50%;
  height: @size;
  width: @size;
}
.icon {
  .circle(1rem);
  background: red;
}
```

I'm trying to reproduce the same approach in `styled-jsx`:
```jsx
function circle(size) {
  /* language=SCSS */
  return css`
    border-radius: 50%;
    height: ${size};
    width: ${size};
  `
}

/* language=SCSS */
let styles = css`
  .icon {
    ${circle(1rem)}
    background: red;
  }
`
```

#### What is the expected behavior?

I expect that the result CSS will be following:
```css
.icon {
    border-radius: 50%;
    height: 1rem;
    width: 1rem;
    background: red;
  }
```

But instead getting an error

`Invalid CSS after "": expected 1 selector or at-rule, was "border-radius: 50%;"`

I would appreciate if you suggest another approach or the correct syntax.

#### Environment (include versions)

* OS: MacOS
* Browser: Chrome 81
* styled-jsx (version): 3.2.4

#### Did this work in previous versions?

I don't know
