### ISSUE TITLE
Quoted properties unexpectedly escaped

### ISSUE THREAD

**Issue by joelburget** [zeit/styled-jsx#70]
### input

```css
.host {
  font-family: 'Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera San';
}
h1::before {
  content: '# ';
}
```

### the style i see
```css
.host {
  font-family: &#x27;Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera San&#x27;;
}
h1::before {
  content: &#x27;# &#x27;;
}
```

I added the following to the `transform.css` fixture:

```css
h1::before {
  font-family: 'Menlo, sans-serif';
  content: '# ';
}
```

The result was properly quoted (`h1[data-jsx="woot"]::before {font-family: 'Menlo, sans-serif';content: '# ';}`), so the escaping must happen after that, when injecting into the page.
